-- Production seed data for Service Catalog Runtime
-- Date: 2026-05-15

INSERT INTO ops.service_catalog_items (
  catalog_id, name, brand, business_group, offer_type, lifecycle_stage,
  customer_segment, problem_statement, promised_outcome, inclusions, exclusions,
  prerequisites, intake_requirements, fulfilment_steps, delivery_owner, agent_roles,
  systems_touched, data_touched, authority_required, risk_class, evidence_required,
  telemetry_required, price_model, cost_drivers, margin_notes, support_model, sla,
  audit_status, last_refreshed_at, instruction_sha, evidence_ref
) VALUES
(
  'OR-RB-001', 'Reading Buddy', 'Outcome Ready', 'MISSION', 'service', 'OFFER_READY',
  ARRAY['parents','schools','providers','children requiring reading support'],
  'Families and providers need a clearer, evidence-backed reading support pathway that can be explained, delivered, measured, and improved.',
  'A structured reading support service with intake, delivery, evidence capture, QA, and customer handover.',
  ARRAY['intake checklist','reading support pathway','delivery workflow','evidence capture','handover summary'],
  ARRAY['clinical diagnosis','guaranteed funding approval','regulated medical advice'],
  ARRAY['customer consent','basic learner profile','delivery capacity','evidence storage location'],
  ARRAY['participant profile','goals','current reading context','support constraints','consent'],
  ARRAY['intake','qualification','support plan creation','delivery session workflow','evidence capture','QA review','handover','follow-up'],
  'Outcome Ready',
  ARRAY['catalog_curator','intake_assessor','fulfilment_operator','evidence_collector','QA_reviewer','support_agent'],
  ARRAY['Vercel','Supabase','Command Centre','Google Drive','GitHub'],
  ARRAY['customer profile','support notes','evidence artifacts','delivery status'],
  'LOG','HIGH',
  ARRAY['catalog record','intake record','delivery record','evidence artifact','QA receipt','handover artifact'],
  ARRAY['intake count','delivery status','evidence completion','customer outcome','support follow-up'],
  'tiered', ARRAY['delivery time','QA time','support load','platform usage'],
  'Margin depends on delivery labour and automation coverage. Requires package pricing before ACTIVE.',
  'guided','TBD',
  'PARTIAL', now(), 'bootstrap-v1', 'github:ops/service_catalog_runtime/01_seed.sql'
),
(
  'AHC-SP-001', 'Augmented Humanity Coach Service Packs', 'Augmented Humanity Coach', 'CORE', 'pack', 'OFFER_READY',
  ARRAY['small business','enterprise teams','government teams','executives','operations leaders'],
  'Organisations need practical AI augmentation services that convert intent into operating capability without losing human accountability.',
  'A packaged service catalogue for AI augmentation, workflow uplift, agent readiness, and operating model improvement.',
  ARRAY['discovery pack','workflow mapping','agent opportunity map','implementation roadmap','governance checklist','handover pack'],
  ARRAY['unapproved production deployment','legal sign-off','regulated advice','credential custody unless separately authorised'],
  ARRAY['business sponsor','workflow scope','current tools list','risk constraints','authority boundary'],
  ARRAY['organisation profile','process area','pain points','tools','data sensitivity','decision authority'],
  ARRAY['discovery','catalog mapping','workflow analysis','augmentation design','implementation plan','governance review','handover'],
  'Augmented Humanity Coach',
  ARRAY['offer_architect','workflow_mapper','agent_designer','governance_reviewer','QA_reviewer','renewal_agent'],
  ARRAY['GitHub','Supabase','Command Centre','Vercel','Google Drive'],
  ARRAY['business process metadata','workflow notes','tool inventory','risk register'],
  'LOG','HIGH',
  ARRAY['catalog record','workflow map','agent opportunity matrix','governance checklist','customer handover'],
  ARRAY['pipeline stage','pack completion','customer actions','reuse opportunities','conversion'],
  'fixed', ARRAY['consulting time','automation build time','QA','support'],
  'Needs fixed pack tiers and margin validation before ACTIVE.',
  'guided','TBD',
  'PARTIAL', now(), 'bootstrap-v1', 'github:ops/service_catalog_runtime/01_seed.sql'
),
(
  'WFA-WF-001', 'WorkFamilyAI Workforce Role Products', 'WorkFamilyAI', 'CORE', 'subscription', 'OFFER_READY',
  ARRAY['leaders','HR teams','operations teams','transformation teams','service teams'],
  'Teams need clearer mapping between human roles, work families, AI support, accountability, and service delivery outcomes.',
  'A role and workforce product suite that maps work, support patterns, agent roles, and improvement opportunities.',
  ARRAY['role map','work family model','AI support map','leadership view','team operating pack','improvement backlog'],
  ARRAY['HR legal determination','employment law advice','automated termination or disciplinary decisioning'],
  ARRAY['organisation structure','role list','work area','leadership sponsor','privacy constraints'],
  ARRAY['team context','role descriptions','pain points','systems used','risk boundaries'],
  ARRAY['role intake','work mapping','agent support mapping','leader review','QA','handover','renewal review'],
  'WorkFamilyAI',
  ARRAY['catalog_curator','role_mapper','agent_support_mapper','QA_reviewer','support_agent','renewal_agent'],
  ARRAY['Supabase','Command Centre','GitHub','Vercel','Google Drive'],
  ARRAY['role metadata','team structure','workflow notes','support mapping'],
  'LOG','HIGH',
  ARRAY['catalog record','role map','support map','leader handover','QA receipt'],
  ARRAY['roles mapped','support opportunities','leader actions','subscription status','renewal signals'],
  'subscription', ARRAY['mapping time','support time','platform usage','QA'],
  'Subscription economics require tier definition and usage telemetry before ACTIVE.',
  'managed','TBD',
  'PARTIAL', now(), 'bootstrap-v1', 'github:ops/service_catalog_runtime/01_seed.sql'
)
ON CONFLICT (catalog_id) DO UPDATE SET
  lifecycle_stage = EXCLUDED.lifecycle_stage,
  customer_segment = EXCLUDED.customer_segment,
  problem_statement = EXCLUDED.problem_statement,
  promised_outcome = EXCLUDED.promised_outcome,
  inclusions = EXCLUDED.inclusions,
  exclusions = EXCLUDED.exclusions,
  prerequisites = EXCLUDED.prerequisites,
  intake_requirements = EXCLUDED.intake_requirements,
  fulfilment_steps = EXCLUDED.fulfilment_steps,
  delivery_owner = EXCLUDED.delivery_owner,
  agent_roles = EXCLUDED.agent_roles,
  systems_touched = EXCLUDED.systems_touched,
  data_touched = EXCLUDED.data_touched,
  authority_required = EXCLUDED.authority_required,
  risk_class = EXCLUDED.risk_class,
  evidence_required = EXCLUDED.evidence_required,
  telemetry_required = EXCLUDED.telemetry_required,
  price_model = EXCLUDED.price_model,
  cost_drivers = EXCLUDED.cost_drivers,
  margin_notes = EXCLUDED.margin_notes,
  support_model = EXCLUDED.support_model,
  sla = EXCLUDED.sla,
  audit_status = EXCLUDED.audit_status,
  last_refreshed_at = now(),
  instruction_sha = EXCLUDED.instruction_sha,
  evidence_ref = EXCLUDED.evidence_ref,
  updated_at = now();

INSERT INTO ops.runtime_execution_receipts (task_id, action, status, result, evidence, gaps, next_action)
VALUES (
  'service-catalog-runtime-seed-2026-05-15',
  'seed_initial_catalog_items',
  'PARTIAL',
  '{"seeded_catalog_ids":["OR-RB-001","AHC-SP-001","WFA-WF-001"]}'::jsonb,
  '{"source":"ops/service_catalog_runtime/01_seed.sql"}'::jsonb,
  ARRAY['pricing tiers incomplete','SLA incomplete','runtime deployment receipt required'],
  'Deploy schema and seed through Bridge, then run smoke tests.'
);
