-- T4H Runtime Ledger — Supabase sink table
-- Apps Script Runtime mirrors every receipt here for canonical truth.
-- Sheet is local ledger; Supabase is enterprise ledger.
--
-- Constitution: GLOBAL_RULE_KERNEL_V6
--   - ledger_must_be_runtime_canonical
--   - no_unobserved_execution
--   - REAL / PARTIAL / BLOCKED only (PRETEND forbidden by check constraint)

create table if not exists public.reality_ledger (
  id              bigint generated by default as identity primary key,
  occurred_at     timestamptz not null default now(),
  inserted_at     timestamptz not null default now(),
  actor_id        text not null,
  tenant_id       text not null,
  runtime_id      text not null,
  execution_id    text,
  nonce           text,
  state           text not null check (state in ('REAL','PARTIAL','BLOCKED')),
  tier            text check (tier in ('HOT','HIGH','NORMAL','LOW')),
  event           text not null,
  evidence_type   text,
  evidence        text,
  duration_ms     integer,
  folders_seen    integer,
  folders_processed integer,
  error           text
);

create index if not exists reality_ledger_runtime_idx on public.reality_ledger (runtime_id, occurred_at desc);
create index if not exists reality_ledger_state_idx   on public.reality_ledger (state, occurred_at desc);
create index if not exists reality_ledger_actor_idx   on public.reality_ledger (actor_id, occurred_at desc);

-- RLS: service-role only by default. Apps Script uses service-role key.
alter table public.reality_ledger enable row level security;

drop policy if exists reality_ledger_service on public.reality_ledger;
create policy reality_ledger_service on public.reality_ledger
  for all to service_role using (true) with check (true);

-- Health view: latest state per runtime
create or replace view public.v_runtime_health as
select distinct on (runtime_id)
  runtime_id,
  state,
  tier,
  event,
  occurred_at,
  evidence,
  folders_processed,
  duration_ms,
  error
from public.reality_ledger
order by runtime_id, occurred_at desc;

-- Survivability proof: count consecutive REAL ticks per runtime
create or replace view public.v_runtime_survivability as
with ticks as (
  select runtime_id, occurred_at, state,
         lag(state) over (partition by runtime_id order by occurred_at) as prev_state
  from public.reality_ledger
  where event in ('tick_complete','scan_complete')
)
select runtime_id,
       count(*) filter (where state = 'REAL') as healthy_ticks,
       max(occurred_at) as last_tick,
       (count(*) filter (where state = 'REAL'))::float / nullif(count(*),0) as healthy_ratio
from ticks
where occurred_at > now() - interval '7 days'
group by runtime_id;
