#!/usr/bin/env python3
"""Reconcile LLM export candidates without deleting or hydrating cloud files.

Consumes the metadata-only TSV generated by the LLM archive search. Hashes only
files that are locally materialised and readable, groups exact duplicates within
an account scope, identifies incomplete/placeholder artefacts, and emits a
plan that is never executed automatically.

Important policy: Gmail and T4H account exports are separate required source
families. Even when hashes match, one canonical copy is retained per account.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path


def sha256_file(path: Path, chunk_size: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(chunk_size):
            digest.update(chunk)
    return digest.hexdigest()


def read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def account_scope(path: Path) -> str:
    text = str(path)
    if "GoogleDrive-troy.latter@gmail.com" in text:
        return "GMAIL"
    if "GoogleDrive-troy@tech4humanity.com.au" in text:
        return "T4H"
    if "/Desktop/" in text:
        return "MAC_DESKTOP"
    if "iCloud Drive" in text:
        return "ICLOUD"
    return "OTHER"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inventory", required=True, type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--min-free-gb", type=float, default=5.0)
    args = parser.parse_args()

    inventory = args.inventory.expanduser().resolve()
    output_dir = (args.output_dir or inventory.parent / "reconciliation").expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = read_tsv(inventory)
    statvfs = os.statvfs(str(Path.home()))
    free_bytes = statvfs.f_bavail * statvfs.f_frsize
    hashing_allowed = free_bytes >= int(args.min_free_gb * 1024**3)

    enriched: list[dict[str, str]] = []
    scoped_hashes: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    global_hashes: dict[str, list[dict[str, str]]] = defaultdict(list)

    for row in rows:
        path = Path(row.get("path", ""))
        classification = row.get("classification", "")
        result = dict(row)
        scope = account_scope(path)
        result.update({
            "account_scope": scope,
            "exists": "false",
            "readable": "false",
            "sha256": "",
            "hash_status": "NOT_ATTEMPTED",
            "recommended_action": "REVIEW",
            "reason": "",
        })

        try:
            exists = path.is_file()
        except OSError:
            exists = False
        result["exists"] = str(exists).lower()

        if classification == "INCOMPLETE_DOWNLOAD" or path.name.lower().endswith(".crdownload"):
            result["recommended_action"] = "DELETE_AFTER_GAP_REGISTERED"
            result["reason"] = "Incomplete browser download; not canonical evidence."
        elif classification == "TINY_ZIP_OR_PLACEHOLDER" or (path.suffix.lower() == ".zip" and int(row.get("bytes") or 0) < 1024):
            result["recommended_action"] = "DELETE_AFTER_RECEIPT"
            result["reason"] = "Tiny ZIP or placeholder; retain only a receipt of its existence."
        elif not exists:
            result["recommended_action"] = "RETAIN_REFERENCE"
            result["reason"] = "Cloud placeholder or inaccessible file; hash deferred."
        elif not hashing_allowed:
            result["recommended_action"] = "RETAIN_PENDING_HASH"
            result["reason"] = "Disk free-space gate prevented hashing."
            result["hash_status"] = "BLOCKED_LOW_DISK"
        else:
            try:
                digest = sha256_file(path)
                result["readable"] = "true"
                result["sha256"] = digest
                result["hash_status"] = "HASHED"
                result["recommended_action"] = "RETAIN_UNIQUE_PENDING_S3"
                scoped_hashes[(scope, digest)].append(result)
                global_hashes[digest].append(result)
            except (OSError, PermissionError) as exc:
                result["hash_status"] = "READ_FAILED"
                result["recommended_action"] = "RETAIN_RETRY"
                result["reason"] = str(exc)[:300]

        enriched.append(result)

    duplicate_groups = []
    for (scope, digest), group in scoped_hashes.items():
        if len(group) < 2:
            continue
        preferred = sorted(
            group,
            key=lambda item: (
                "Shared drives/T4H1" not in item.get("path", ""),
                "My Drive" not in item.get("path", ""),
                "Desktop" in item.get("root", ""),
                -int(item.get("modified_epoch") or 0),
            ),
        )[0]
        for item in group:
            if item is preferred:
                item["recommended_action"] = "RETAIN_CANONICAL_ACCOUNT_COPY_PENDING_S3"
                item["reason"] = f"Preferred {scope} canonical copy for SHA-256 {digest}."
            else:
                item["recommended_action"] = "DELETE_AFTER_S3_VERIFY"
                item["reason"] = f"Exact duplicate within {scope} of {preferred.get('path', '')}."
        duplicate_groups.append({
            "account_scope": scope,
            "sha256": digest,
            "bytes": int(preferred.get("bytes") or 0),
            "copies": len(group),
            "canonical_path": preferred.get("path", ""),
            "duplicate_paths": [x.get("path", "") for x in group if x is not preferred],
        })

    cross_account_matches = []
    for digest, group in global_hashes.items():
        scopes = sorted({item.get("account_scope", "OTHER") for item in group})
        if len(scopes) < 2:
            continue
        cross_account_matches.append({
            "sha256": digest,
            "bytes": int(group[0].get("bytes") or 0),
            "account_scopes": scopes,
            "paths": [item.get("path", "") for item in group],
            "policy": "RETAIN_ONE_CANONICAL_COPY_PER_ACCOUNT_SCOPE",
        })

    fields = list(enriched[0].keys()) if enriched else []
    reconciled_path = output_dir / "llm_export_reconciled.tsv"
    with reconciled_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t")
        writer.writeheader()
        writer.writerows(enriched)

    delete_plan_path = output_dir / "delete_plan.tsv"
    delete_rows = [r for r in enriched if r["recommended_action"].startswith("DELETE_")]
    with delete_plan_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t")
        writer.writeheader()
        writer.writerows(delete_rows)

    summary = {
        "status": "REAL",
        "mode": "PLAN_ONLY_NO_DELETION_NO_UPLOAD",
        "inventory": str(inventory),
        "free_bytes": free_bytes,
        "hashing_allowed": hashing_allowed,
        "candidate_rows": len(rows),
        "hashed_files": sum(1 for r in enriched if r["hash_status"] == "HASHED"),
        "account_scope_counts": dict(Counter(r["account_scope"] for r in enriched)),
        "duplicate_groups_within_account": len(duplicate_groups),
        "duplicate_copies_within_account": sum(max(0, g["copies"] - 1) for g in duplicate_groups),
        "cross_account_same_hash_groups": len(cross_account_matches),
        "delete_plan_rows": len(delete_rows),
        "actions": dict(Counter(r["recommended_action"] for r in enriched)),
        "reconciled_manifest": str(reconciled_path),
        "delete_plan": str(delete_plan_path),
        "duplicate_groups_file": str(output_dir / "duplicate_groups.json"),
        "cross_account_matches_file": str(output_dir / "cross_account_matches.json"),
        "policy": "Retain one canonical GPT and Claude export family per account: Gmail and T4H.",
        "next_gate": "Verify each account-scoped canonical object in S3 before executing any delete-plan row.",
    }

    (output_dir / "duplicate_groups.json").write_text(
        json.dumps(duplicate_groups, indent=2) + "\n", encoding="utf-8"
    )
    (output_dir / "cross_account_matches.json").write_text(
        json.dumps(cross_account_matches, indent=2) + "\n", encoding="utf-8"
    )
    (output_dir / "summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
