-- =====================================================================
-- SUPERSEDED 2026-05-19 — DO NOT APPLY.
--
-- This file's original design created curriculum tables in the PUBLIC
-- schema. It was committed (commit b25487fa) but was NEVER applied to
-- any database. It is superseded by the deployed, runtime-true design:
--
--   supabase/migrations/20260519_curriculum_object_registry_v2.sql
--   (curriculum.* schema; text natural keys; hard anti-fabrication;
--    full asset taxonomy; 10-product boundary semantics; PRETEND
--    removed per kernel forbidden_states)
--
-- Applied to Supabase project lzfgigiyqpuuxslsygjt as migration
-- name 'curriculum_object_registry_v2_merged'. v1 schema retained as
-- curriculum_archived_v1 (archive-never-delete).
--
-- This file is intentionally reduced to a no-op so that running the
-- migrations directory does not create conflicting public.* tables.
-- =====================================================================

SELECT 'superseded: see 20260519_curriculum_object_registry_v2.sql' AS migration_status;
