#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone

PROJECT_TYPES = {"research", "product", "business", "website", "experiment", "policy", "service"}
LIFECYCLE = ["IDEA", "DISCOVERY", "RESEARCH", "BUILD", "VALIDATE", "PILOT", "PRODUCTION", "OPERATE", "ARCHIVE"]
REQUIRED_DIRS = ["docs", "research", "evidence", "runtime", "data", "assets", "src", "tests", ".github/workflows", "docker", "infra"]
REQUIRED_FILES = ["README.md", "project.yaml", "evidence.yaml", "governance.yaml", "runtime.yaml", "CHANGELOG.md", "LICENSE", "Dockerfile", ".github/workflows/validate.yml", "tests/test_structure.py"]


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if not slug:
        raise ValueError("project name must contain letters or numbers")
    return slug


def write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def project_yaml(slug: str, name: str, project_type: str, owner: str) -> str:
    return f"""schema_version: cbk.project.v0.1
project:
  id: {slug}
  name: {name}
  type: {project_type}
  owner: {owner}
  lifecycle: IDEA
  created_at: {datetime.now(timezone.utc).isoformat()}
  runtime:
    provider_neutral: true
    receipts_required: true
  evidence:
    proof_before_real: true
  repositories: []
  environments:
    - development
    - test
    - production
"""


def generate(project_type: str, name: str, output: pathlib.Path, owner: str, force: bool) -> pathlib.Path:
    if project_type not in PROJECT_TYPES:
        raise ValueError(f"unsupported project type: {project_type}")
    slug = slugify(name)
    target = output / slug
    if target.exists():
        if not force:
            raise FileExistsError(f"target exists: {target}")
        shutil.rmtree(target)
    for directory in REQUIRED_DIRS:
        (target / directory).mkdir(parents=True, exist_ok=True)
    write(target / "project.yaml", project_yaml(slug, name, project_type, owner))
    write(target / "evidence.yaml", "schema_version: cbk.evidence.v0.1\nstate: PARTIAL\nreceipts: []\nclaims: []\n")
    write(target / "governance.yaml", f"schema_version: cbk.governance.v0.1\nowner: {owner}\nauthority: owner\ntruth_rule: no_receipt_not_real\n")
    write(target / "runtime.yaml", "schema_version: cbk.runtime.v0.1\nprovider_neutral: true\nworkers: []\nqueues: []\ntelemetry: required\nrecovery: required\n")
    write(target / "README.md", f"# {name}\n\nType: `{project_type}`\n\nGenerated by Canonical Bootstrap Kit v0.1.\n")
    write(target / "CHANGELOG.md", "# Changelog\n\n## 0.1.0\n\n- Canonical project created.\n")
    write(target / "LICENSE", "Proprietary - Tech 4 Humanity Pty Ltd\n")
    write(target / "Dockerfile", "FROM python:3.12-slim\nWORKDIR /app\nCOPY . .\nCMD [\"python3\", \"-m\", \"unittest\", \"discover\", \"-s\", \"tests\"]\n")
    write(target / ".gitignore", "__pycache__/\n*.pyc\n.env\nreceipts/*.tmp\n")
    write(target / "docs/index.md", f"# {name}\n\nCanonical documentation root.\n")
    write(target / "research/README.md", "# Research\n\nHypotheses, variables, measures, studies and references.\n")
    write(target / "evidence/README.md", "# Evidence\n\nReceipts, claims, provenance and runtime proof.\n")
    write(target / "runtime/README.md", "# Runtime\n\nWorkers, queues, telemetry, state and recovery.\n")
    write(target / "tests/test_structure.py", """import pathlib\nimport unittest\n\nROOT = pathlib.Path(__file__).resolve().parents[1]\n\nclass StructureTest(unittest.TestCase):\n    def test_required_files(self):\n        required = ['project.yaml','evidence.yaml','governance.yaml','runtime.yaml','README.md']\n        self.assertEqual([], [name for name in required if not (ROOT / name).exists()])\n\nif __name__ == '__main__':\n    unittest.main()\n""")
    write(target / ".github/workflows/validate.yml", """name: Validate Canonical Project\non: [push, pull_request, workflow_dispatch]\npermissions:\n  contents: read\njobs:\n  validate:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: '3.12'\n      - run: python3 -m unittest discover -s tests\n""")
    return target


def parse_scalar(text: str, key: str) -> str | None:
    match = re.search(rf"^\s*{re.escape(key)}:\s*([^#\n]+)", text, re.M)
    return match.group(1).strip() if match else None


def validate(target: pathlib.Path) -> dict:
    missing_dirs = [p for p in REQUIRED_DIRS if not (target / p).is_dir()]
    missing_files = [p for p in REQUIRED_FILES if not (target / p).is_file()]
    errors: list[str] = []
    if missing_dirs:
        errors.append("missing directories: " + ", ".join(missing_dirs))
    if missing_files:
        errors.append("missing files: " + ", ".join(missing_files))
    project_text = (target / "project.yaml").read_text() if (target / "project.yaml").exists() else ""
    project_type = parse_scalar(project_text, "type")
    lifecycle = parse_scalar(project_text, "lifecycle")
    schema = parse_scalar(project_text, "schema_version")
    if schema != "cbk.project.v0.1":
        errors.append("invalid project schema_version")
    if project_type not in PROJECT_TYPES:
        errors.append("invalid project type")
    if lifecycle not in LIFECYCLE:
        errors.append("invalid lifecycle")
    for filename in ["evidence.yaml", "governance.yaml", "runtime.yaml"]:
        if (target / filename).exists() and "schema_version:" not in (target / filename).read_text():
            errors.append(f"missing schema_version in {filename}")
    return {"valid": not errors, "errors": errors, "missing_dirs": missing_dirs, "missing_files": missing_files}


def compile_project(target: pathlib.Path) -> dict:
    result = validate(target)
    if not result["valid"]:
        raise RuntimeError("validation failed: " + "; ".join(result["errors"]))
    files = sorted(str(p.relative_to(target)) for p in target.rglob("*") if p.is_file() and not p.parts[-1].endswith(".pyc"))
    hashes = {name: hashlib.sha256((target / name).read_bytes()).hexdigest() for name in files}
    manifest = {
        "schema_version": "cbk.manifest.v0.1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "project": target.name,
        "files": hashes,
        "content_hash": hashlib.sha256(json.dumps(hashes, sort_keys=True).encode()).hexdigest(),
    }
    build = target / "build"
    build.mkdir(exist_ok=True)
    write(build / "manifest.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    write(build / "index.html", f"<!doctype html><html><body><h1>{target.name}</h1><p>Canonical project compiled.</p><code>{manifest['content_hash']}</code></body></html>\n")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(prog="cbk")
    sub = parser.add_subparsers(dest="command", required=True)
    new = sub.add_parser("new")
    new.add_argument("project_type", choices=sorted(PROJECT_TYPES))
    new.add_argument("name")
    new.add_argument("--output", default=".")
    new.add_argument("--owner", default="Troy Latter")
    new.add_argument("--force", action="store_true")
    val = sub.add_parser("validate")
    val.add_argument("target")
    comp = sub.add_parser("compile")
    comp.add_argument("target")
    args = parser.parse_args()
    try:
        if args.command == "new":
            target = generate(args.project_type, args.name, pathlib.Path(args.output).resolve(), args.owner, args.force)
            print(json.dumps({"created": str(target), "status": "PARTIAL"}, indent=2))
        elif args.command == "validate":
            result = validate(pathlib.Path(args.target).resolve())
            print(json.dumps(result, indent=2))
            return 0 if result["valid"] else 1
        elif args.command == "compile":
            print(json.dumps(compile_project(pathlib.Path(args.target).resolve()), indent=2))
        return 0
    except Exception as exc:
        print(json.dumps({"error": str(exc)}, indent=2), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
