-- promoted_from: bridge_jobs/outcome_ready_activity_seed_pack_10_more_20260429.sql
-- promoted_at_utc: 2026-05-06T00:00:00Z
-- env: prod
-- status: PROMOTED_TO_PROD
-- Execute this SQL in Supabase prod environment via troy-sql-executor
-- Source file: bridge_jobs/outcome_ready_activity_seed_pack_10_more_20260429.sql
-- Run after: outcome_ready_neuroprofile_activity_engine migration is applied
